### PR TITLE
Prepare pytango 9.3.2

### PR DESCRIPTION
**Pull request by bourtemb**

### CODE REVIEW

**Comment by bourtemb** [comment]
We got a compilation error during the building phase of the package:

`[...]/bin/ld: cannot find -lboost_python`

https://github.com/tango-controls/pytango-conda-recipes/runs/674079033?check_suite_focus=true#step:6:1080

Do you think this is coming from the conda recipe of from a recent change in pytango?

**Comment by ajoubertza** [comment]
> Do you think this is coming from the conda recipe of from a recent change in pytango?

It is the recipe, but could also be fixed in pytango.  The difference between the environment created for the pytango Travis tests (which work), and this recipe is the use of the conda-forge channel.  If we install boost from "standard" conda, we get a slightly earlier version which works.

#### "Standard" install:
```
$ docker run -it --rm continuumio/miniconda3 /bin/bash
(base) root@304c6a2860b8:/# conda install boost
...
(base) root@304c6a2860b8:/# ls -lo /opt/conda/lib/libboost_python*
lrwxrwxrwx 1 root     19 May 15 06:01 /opt/conda/lib/libboost_python.a -> libboost_python37.a
lrwxrwxrwx 1 root     27 May 15 06:01 /opt/conda/lib/libboost_python.so -> libboost_python37.so.1.67.0
-rw-rw-r-- 2 root 577386 Jul  5  2018 /opt/conda/lib/libboost_python37.a
lrwxrwxrwx 1 root     27 May 15 06:01 /opt/conda/lib/libboost_python37.so -> libboost_python37.so.1.67.0
-rwxrwxr-x 2 root 327560 Jul  5  2018 /opt/conda/lib/libboost_python37.so.1.67.0

```

#### conda-forge install:
```
$ docker run -it --rm -v $PWD:/opt/current continuumio/miniconda3 /bin/bash
(base) root@e6b7a347df09:/# conda install -c conda-forge boost
...
(base) root@e6b7a347df09:/# ls -lo /opt/conda/lib/libboost_python*
-rw-rw-r-- 2 root 715336 Feb 19 07:54 /opt/conda/lib/libboost_python37.a
lrwxrwxrwx 1 root     27 May 15 06:27 /opt/conda/lib/libboost_python37.so -> libboost_python37.so.1.72.0
lrwxrwxrwx 1 root     27 May 15 06:27 /opt/conda/lib/libboost_python37.so.1 -> libboost_python37.so.1.72.0
lrwxrwxrwx 1 root     27 May 15 06:27 /opt/conda/lib/libboost_python37.so.1.72 -> libboost_python37.so.1.72.0
-rwxrwxr-x 2 root 324592 Feb 19 07:55 /opt/conda/lib/libboost_python37.so.1.72.0
```

So we see the `libboost_python.so` symlink is missing.  Options to fix the recipe:
- add the symlink manually before building, or
- install boost from standard conda

We could also improve pytango to handle this.  I did for the Linux installs, but not for conda, since it didn't appear to be necessary.   However, this improvement would only be available in a future pytango release.

**Comment by bourtemb** [comment]
> > Do you think this is coming from the conda recipe of from a recent change in pytango?
> 
> It is the recipe, but could also be fixed in pytango. The difference between the environment created for the pytango Travis tests (which work), and this recipe is the use of the conda-forge channel. If we install boost from "standard" conda, we get a slightly earlier version which works.

Good point.
This is actually reminding me that the DockerFile that @tiagocoutinho was using to build the tango conda package for gitlab-ci was removing conda-forge from the list of channels:
https://github.com/tango-controls/tango-conda-recipes/blob/master/Dockerfile

@tiagocoutinho could you please comment on the original reasons to ignore conda-forge?

The problem is that we now have a new dependency to cppzmq (because zmq.hpp file is no longer provided by cppTango). It seemed natural to me to use conda-forge for that, to get recent versions of cppzmq and omniorb too but this is causing some other issues obviously as we are seeing with this libboost-python from conda-forge.

**Comment by ajoubertza** [comment]
Another option is to pin the boost version, maybe to `<=1.67.0`.  Even if we get that from conda-forge it looks OK:
```
(base) root@c4ba388b34ce:/# conda install -c conda-forge boost==1.67.0
...
(base) root@c4ba388b34ce:/# ls -lo /opt/conda/lib/libboost_python*
lrwxrwxrwx 1 root     19 May 15 11:08 /opt/conda/lib/libboost_python.a -> libboost_python37.a
lrwxrwxrwx 1 root     27 May 15 11:08 /opt/conda/lib/libboost_python.so -> libboost_python37.so.1.67.0
-rw-rw-r-- 2 root 577386 Jul  5  2018 /opt/conda/lib/libboost_python37.a
lrwxrwxrwx 1 root     27 May 15 11:08 /opt/conda/lib/libboost_python37.so -> libboost_python37.so.1.67.0
-rwxrwxr-x 2 root 327560 Jul  5  2018 /opt/conda/lib/libboost_python37.so.1.67.0
```

**Comment by bourtemb** [comment]
@ajoubertza I tried to pin boost version to <=1.67.0 as you suggested.
It compiled it seems but now the Github workflow seems to fail because of some failing tests.
Do we expect all the tests to pass?

**Comment by ajoubertza** [comment]
> Do we expect all the tests to pass?

Yes, although I have only run the tests against cppTango 9.3.2.  Looking at the logs, the first problem is the missing `TangoTest` executable.   We'll need tango-controls/tango-conda-recipes/pull/5.  I'll review that one.

**Comment by bourtemb** [comment]
@ajoubertza I uploaded tango-test package to tango-controls conda channel and I added a dependency to tango-test for the tests, the github workflow log looks much better now.
I have seen there is a patch which is applied during the pytango conda package build for the tests (See https://github.com/tango-controls/pytango-conda-recipes/blob/master/pytango/test.patch file).
Do you think this patch is still required? It does not seem up to date.
Could you please have a look?

**Comment by ajoubertza** [comment]
@bourtemb I don't think that patch is required.  The gevent tests pass on Python 2.7 in Travis, at least.

**Comment by bourtemb** [comment]
I removed the patch file and now the github workflow is failing.
But the failure does not seem to be due to the changes in the latest commit.
The conda versions used to build the package seems to have changed since the last time the github workflow was executed (4 days ago).
It seems it is using a version using python 3.8 instead of 3.7 before:

Here is the differences in the packages installed when installing conda-build:

```
   _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
-  beautifulsoup4     pkgs/main/linux-64::beautifulsoup4-4.9.0-py37_0
+  beautifulsoup4     pkgs/main/linux-64::beautifulsoup4-4.9.0-py38_0
   bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
   ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
-  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py37_0
-  cffi               pkgs/main/linux-64::cffi-1.14.0-py37he30daa8_1
-  chardet            pkgs/main/linux-64::chardet-3.0.4-py37_1003
-  conda              pkgs/main/linux-64::conda-4.8.3-py37_0
-  conda-build        pkgs/main/linux-64::conda-build-3.18.11-py37_0
-  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.6.1-py37h7b6447c_0
-  cryptography       pkgs/main/linux-64::cryptography-2.9.2-py37h1ba5d50_0
+  certifi            pkgs/main/linux-64::certifi-2020.4.5.1-py38_0
+  cffi               pkgs/main/linux-64::cffi-1.14.0-py38he30daa8_1
+  chardet            pkgs/main/linux-64::chardet-3.0.4-py38_1003
+  conda              pkgs/main/linux-64::conda-4.8.3-py38_0
+  conda-build        pkgs/main/linux-64::conda-build-3.18.11-py38_0
+  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.6.1-py38h7b6447c_0
+  cryptography       pkgs/main/linux-64::cryptography-2.9.2-py38h1ba5d50_0
   filelock           pkgs/main/noarch::filelock-3.0.12-py_0
   glob2              pkgs/main/noarch::glob2-0.7-py_0
   idna               pkgs/main/noarch::idna-2.9-py_1
@@ -24,35 +24,36 @@
   libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
   libxml2            pkgs/main/linux-64::libxml2-2.9.9-hea5a465_1
   lz4-c              pkgs/main/linux-64::lz4-c-1.9.2-he6710b0_0
-  markupsafe         pkgs/main/linux-64::markupsafe-1.1.1-py37h7b6447c_0
+  markupsafe         pkgs/main/linux-64::markupsafe-1.1.1-py38h7b6447c_0
   ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
   openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
   patchelf           pkgs/main/linux-64::patchelf-0.10-he6710b0_0
-  pip                pkgs/main/linux-64::pip-20.0.2-py37_3
-  pkginfo            pkgs/main/linux-64::pkginfo-1.5.0.1-py37_0
-  psutil             pkgs/main/linux-64::psutil-5.7.0-py37h7b6447c_0
-  py-lief            pkgs/main/linux-64::py-lief-0.10.1-py37h403a769_0
-  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py37h7b6447c_0
+  pip                pkgs/main/linux-64::pip-20.0.2-py38_3
+  pkginfo            pkgs/main/linux-64::pkginfo-1.5.0.1-py38_0
+  psutil             pkgs/main/linux-64::psutil-5.7.0-py38h7b6447c_0
+  py-lief            pkgs/main/linux-64::py-lief-0.10.1-py38h403a769_0
+  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py38h7b6447c_1
   pycparser          pkgs/main/noarch::pycparser-2.20-py_0
-  pyopenssl          pkgs/main/linux-64::pyopenssl-19.1.0-py37_0
-  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py37_0
-  python             pkgs/main/linux-64::python-3.7.7-hcff3b4d_5
+  pyopenssl          pkgs/main/linux-64::pyopenssl-19.1.0-py38_0
+  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py38_0
+  python             pkgs/main/linux-64::python-3.8.3-hcff3b4d_0
   python-libarchive~ pkgs/main/noarch::python-libarchive-c-2.9-py_0
   pytz               pkgs/main/noarch::pytz-2020.1-py_0
-  pyyaml             pkgs/main/linux-64::pyyaml-5.3.1-py37h7b6447c_0
+  pyyaml             pkgs/main/linux-64::pyyaml-5.3.1-py38h7b6447c_0
   readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
-  requests           pkgs/main/linux-64::requests-2.23.0-py37_0
+  requests           pkgs/main/linux-64::requests-2.23.0-py38_0
   ripgrep            pkgs/main/linux-64::ripgrep-11.0.2-he32d670_0
-  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.87-py37h7b6447c_0
-  setuptools         pkgs/main/linux-64::setuptools-46.2.0-py37_0
-  six                pkgs/main/linux-64::six-1.14.0-py37_0
-  soupsieve          pkgs/main/noarch::soupsieve-2.0-py_0
+  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.87-py38h7b6447c_0
+  setuptools         pkgs/main/linux-64::setuptools-46.4.0-py38_0
+  six                pkgs/main/linux-64::six-1.14.0-py38_0
+  soupsieve          pkgs/main/noarch::soupsieve-2.0.1-py_0
   sqlite             pkgs/main/linux-64::sqlite-3.31.1-h62c20be_1
    tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
   tqdm               pkgs/main/noarch::tqdm-4.46.0-py_0
-  urllib3            pkgs/main/linux-64::urllib3-1.25.8-py37_0
-  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0
+  urllib3            pkgs/main/linux-64::urllib3-1.25.8-py38_0
+  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
   xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
   yaml               pkgs/main/linux-64::yaml-0.1.7-had09818_2
   zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
   zstd               pkgs/main/linux-64::zstd-1.4.4-h0b5b093_3
```

We get new warnings:

```
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING conda.models.version:get_matcher(528): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
[...]
```

We get the following conflicts reported:

```
Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.8
boost[version='<=1.67.0'] -> numpy[version='>=1.9.3,<2.0a0'] -> python[version='>=3.8,<3.9.0a0']
cpptango=9.3 -> omniorb[version='>=4.2.4,<5.0a0'] -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
boost[version='<=1.67.0'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.7,<3.8.0a0']

Package _libgcc_mutex conflicts for:
cpptango=9.3 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
cppzmq -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
python=3.8 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
numpy[version='>=1.1'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']

Package libgcc-ng conflicts for:
python=3.8 -> libgcc-ng[version='>=7.3.0']
cppzmq -> libgcc-ng[version='>=7.3.0']
python=3.8 -> libffi[version='>=3.2.1,<3.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']
numpy[version='>=1.1'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
cpptango=9.3 -> libgcc-ng[version='>=7.3.0']
boost[version='<=1.67.0'] -> boost-cpp=1.67.0 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
numpy[version='>=1.1'] -> libopenblas[version='>=0.3.2,<0.3.3.0a0'] -> libgcc-ng[version='>=8.2.0']
cppzmq -> zeromq[version='>=4.3.1,<4.4.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']

Package numpy conflicts for:
numpy[version='>=1.1']
boost[version='<=1.67.0'] -> numpy[version='1.11.*|1.12.*|1.13.*|>=1.11|>=1.8|>=1.9.3,<2.0a0|>=1.9|>=1.7']
boost[version='<=1.67.0'] -> py-boost==1.67.0=py35h04863e7_4 -> numpy[version='>=1.11.3,<2.0a0']

Package sqlite conflicts for:
python=3.8 -> sqlite[version='>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0']
boost[version='<=1.67.0'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.30.0,<4.0a0|>=3.27.2,<4.0a0|3.9.*|>=3.25.1,<4.0a0']
numpy[version='>=1.1'] -> pypy3.6[version='>=7.3.1'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|>=3.25.1,<4.0a0|>=3.27.2,<4.0a0|>=3.30.0,<4.0a0|3.9.*']

Package libstdcxx-ng conflicts for:
boost[version='<=1.67.0'] -> numpy[version='>=1.9.3,<2.0a0'] -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
boost[version='<=1.67.0'] -> libstdcxx-ng[version='>=4.9']

Package python_abi conflicts for:
boost[version='<=1.67.0'] -> numpy[version='>=1.9.3,<2.0a0'] -> python_abi[version='3.6.*|3.6|3.7.*|3.8.*',build='*_cp38|*_cp36m|*_pypy36_pp73|*_cp37m']
cpptango=9.3 -> omniorb[version='>=4.2.4,<5.0a0'] -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp36m|*_cp38|*_cp37m']
numpy[version='>=1.1'] -> python_abi[version='3.6.*|3.6|3.7.*|3.8.*',build='*_cp38|*_cp36m|*_pypy36_pp73|*_cp37m']

Package zeromq conflicts for:
cppzmq -> zeromq[version='4.2.1|4.2.3|>=4.2.3,<4.3.0a0|>=4.3.1,<4.4.0a0|>=4.3.2,<4.4.0a0']
cpptango=9.3 -> zeromq[version='>=4.3.2,<4.4.0a0|>=4.3.2,<5.0a0']
```

**Comment by bourtemb** [comment]
I suspect the failure is due to a recent update (yesterday) of conda-build package in anaconda channel.
See https://anaconda.org/anaconda/conda-build/files

It looks like the problem is not present if conda-build from conda-forge channel (version 3.19.2) is installed instead.
You can see the workflow log on my fork:
https://github.com/bourtemb/pytango-conda-recipes/runs/699365013

**Comment by ajoubertza** [comment]
I haven't [finished testing](https://github.com/tango-controls/pytango/pull/344) PyTango with Python 3.8 yet, so I'm happy if the Conda package doesn't have support for it either.  I'm not sure if it will help to pin the Python version in `meta.yaml` as that is only used after installing `conda-build`.  We could try something like this:
```
conda install conda-build "python<3.8"
```
The conda forge approach might work now, but I imagine Python 3.8 will be available there at some point as well, so better to limit it explicitly.

**Comment by cpascual** [comment]
Hi, I haven't been able to see where the python versions for which the conda package will be built are defined. Is it in the [gitlab yml](https://github.com/tango-controls/pytango-conda-recipes/blob/master/.gitlab-ci.yml)? or is it in the[ pytango .travis matrix](https://github.com/tango-controls/pytango/blob/develop/.travis.yml)?  or somewhere else?

Anyway, I am interested because it would be extremely useful for taurus if the pytango conda package was built also for python 3.5. The reason we want 3.5 is because that is the version in debian9, which is what we use in ALBA, and we use conda for our CI tests. 

pytango 9.3.1 was not avaliable for py<3.6 and I suspect that this is at the [root of some CI failures in the CI tests of taurus](https://github.com/taurus-org/taurus/pull/1108#issuecomment-631728017)

So my question/request is: could we have pytango 9.3.2 conda package for python 3.5?

PS:  Having pytango9.3.2 for python 2.7 as well would be also nice, but it is not critical for us since we will drop support soon)

**Comment by cpascual** [comment]
Hi, the other day [this request](https://github.com/tango-controls/pytango-conda-recipes/pull/1#issuecomment-634688353) was discussed in the tango-kernel meeting and the requirement was probably not well understood. Let me clarify:

1. The taurus testsuite is run both locally and in Travis-CI **using [tox-conda](https://pypi.org/project/tox-conda/)** for a set of environments (different versions of pythons and different bindings of qt, basically)
2. This requires *conda* packages for pytango compatible with the target python (and one of them of special interest for us is python3.5, because it matches the python used in debian9)
3. The release of pytango 9.3.1 done by @tiagocoutinho did not include python3.5
4. I have been able to create a  python3.5 conda package based on tiago's work by simply creating [a merge request to tiago's gitlab repo, adding a 3.5 job](https://gitlab.com/c-p/pytango-conda-recipes/-/jobs/571161394)

Apart from my own personal interest (for the taurus CI testing) ,IMHO having a conda package matching the python in debian9 (which is used in production in some labs such as ALBA) is a good thing for the tango community (it allows the devs to quickly switch environments to debug issues in an environment closer to that of production), and in principle it should be quite straight-forward to provide.

I would have directly proposed the change myself, but I see that the 9.3.2 release, while based on tiago's 9.3.1 work, was moved to github instead of gitlab. And I haven't been able to see where the build matrix is defined now (before it was in `.gitlab.yml`). If you point me in the right direction I can propose a PR.

Cheers!

**Comment by ajoubertza** [comment]
Thanks @cpascual. That makes sense.  So it will be useful to have conda packages for all those versions.

I see a [build matrix can be defined](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions).  Maybe something like this would work?

```
jobs:
  build:
    name: Build pytango conda packages
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
...
          conda build -c tango-controls $GITHUB_WORKSPACE/pytango --output-folder=$GITHUB_WORKSPACE/dist --python=${{ matrix.python-version }}
```

**Comment by cpascual** [comment]
I am not familiar with github workflows, but it looks like this is exactly it

**Comment by bourtemb** [comment]
> I see a [build matrix can be defined](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions). Maybe something like this would work?
> 
> ```
> jobs:
>   build:
>     name: Build pytango conda packages
>     # This job runs on Linux
>     runs-on: ubuntu-latest
>     strategy:
>       matrix:
>         python-version: [2.7, 3.5, 3.6, 3.7]
> 
>     steps:
> ...
>           conda build -c tango-controls $GITHUB_WORKSPACE/pytango --output-folder=$GITHUB_WORKSPACE/dist --python=${{ matrix.python-version }}
> ```


This is what I tried yesterday in my fork but it does not seem to work.
Conda seems to install python 3.6 even if we precise another version.
This might be due to a bad dependency management in our new conda recipes?
cpptango conda package depends on omniorb conda package which is dependent on some python versions (because providing some python stuff too)?

You can see the logs of my attempt here:

https://github.com/bourtemb/pytango-conda-recipes/runs/731313945

and here with an attempt to give higher priority to tango-controls conda channel over conda-forge (because omniorb conda package on tango-controls conda channel provides a python 3.5 version):

https://github.com/bourtemb/pytango-conda-recipes/runs/733857854

**Comment by cpascual** [comment]
Maybe the versioned dependencies of pytango itself on omniorb are too restrictive on the version and it forces the selection of a python 3.6?

Maybe related: I've noticed that installing pytango via conda tends to resolve to python3.6 unless I explicitly force 3.7

**Comment by weninc** [comment]
adding
export BOOST_PYTHON_LIB=boost_python${PY_VER//./}
to the build.sh should fix the missing boost_python library.
Conda forge doesn't build packages for Python 3.5 anymore so if you need more recent version of dependencies like omniorb you will have to build them yourself.

**Comment by ajoubertza** [comment]
Thanks, @weninc - I forgot about those environment variables (and I added them!).  Details [here](https://github.com/tango-controls/pytango/blob/16a04c2b16d2e7a2ed629bfc746502b8adbcb255/setup.py#L162-L192).

**Review by ajoubertza — APPROVED** [review]
Looks good - thanks @bourtemb!
 
@cpascual you'll be happy to know that the Python 3.5 build is working.

**Comment by cpascual** [comment]
> @cpascual you'll be happy to know that the Python 3.5 build is working.

Thanks a ton!

I'll upload the packages from the artifacts to my own channel to test them using the taurus testsuite in the CI and report back

**Comment by cpascual** [comment]
> I'll upload the packages from the artifacts to my own channel to test them using the taurus testsuite in the CI and report back

The results are good with the taurus CI (usingpy35, py36 and py37)

**Comment by ajoubertza** [comment]
@bourtemb Can you please merge this and upload the files to Anaconda cloud?

**Comment by bourtemb** [comment]
> @bourtemb Can you please merge this and upload the files to Anaconda cloud?

@ajoubertza, Linux 64 pytango conda packages uploaded to tango-controls conda channel!

**Pull request merged**
